var i;var k;var base_url;var stringValue;var strLength;var ch;var display_ch;var baseurl=base_url;function trimSpaces(stringValue){if(stringValue!==''){for(i=0;i<stringValue.length;i++){if(stringValue.charAt(i)!==" "){break;}}
if(i>0){stringValue=stringValue.substring(i);}
strLength=stringValue.length-1;for(i=strLength;i>=0;i--){if(stringValue.charAt(i)!==" "){break;}}
if(i<strLength){stringValue=stringValue.substring(0,i+1);}
stringValue=stringValue.split(' ').join('');}
return stringValue;}
function echeck(str){var at="@";var dot=".";var lat=str.indexOf(at);var lstr=str.length;var ldot=str.indexOf(dot);if(str.indexOf(at)==-1){alert("Invalid E-mail ID");return false;}
if(str.indexOf(at)==-1||str.indexOf(at)===0||str.indexOf(at)==lstr){alert("Invalid E-mail ID");return false;}
if(str.indexOf(dot)==-1||str.indexOf(dot)===0||str.indexOf(dot)==lstr){alert("Invalid E-mail ID");return false;}
if(str.indexOf(at,(lat+1))!==-1){alert("Invalid E-mail ID");return false;}
if(str.substring(lat-1,lat)==dot||str.substring(lat+1,lat+2)==dot){alert("Invalid E-mail ID");return false;}
if(str.indexOf(dot,(lat+2))==-1){alert("Invalid E-mail ID");return false;}
if(str.indexOf(" ")!==-1){alert("Invalid E-mail ID");return false;}
return true;}
function loadPiece(href,divName){$(divName).load(href,function(){var divPaginationLinks=divName+" #pagination a";$(divPaginationLinks).click(function(){var thisHref=$(this).attr("href");loadPiece(thisHref,divName);return false;});});}
function add_row(){var count=$('#upload_count').val();var itemcostval=$('#ptype'+count+'').val();var itemtrackfileval=$('#EDOC'+count+'').val();if(itemcostval==''){alert('Please select EDOC type');return false;}if(itemtrackfileval==''){alert('Please upload EDOC');return false;}
var allow=new Array('doc','docx','pdf');var itemedval=$('#EDOC'+count+'').val();if(itemedval!=''){var ext=$('#EDOC'+count+'').val().split('.').pop().toLowerCase();if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for EDOC '+count+'. Upload file in doc, docx or pdf format!');return false;}}count=parseInt(count)+parseInt(1);var content='';content='<div class="repeat_divouter" id="divrow'+count+'"><div class="float_div1">'+count+'</div><div class="float_div"><select id="ptype'+count+'" class="sel_inner_inputs" name="data[OrderEdocs][ptype][]"><option value="">--Select--</option><option value="C">Escrow docs</option><option value="L">Loan Docs</option><option value="M">MISC</option></select></div><div class="float_div4"><input type="file" name="data[OrderEdocs][edocfile][]" class="inner_input" maxlength="50" value="" id="EDOC'+count+'" /></div>';content+='<div class="float_div" style="width:8%;"><a href="javascript:void(0)" onclick="javascript:delete_row('+count+')" class="delete_btn" title="Remove">Remove</a></div></div>';$('#upload_container').append(content);$('#upload_count').val(count);}
function delete_row(num){var count=$('#upload_count').val();count=parseInt(count);$('#divrow'+count+'').remove();count=parseInt(count)-parseInt(1);$('#upload_count').val(count);if(count<2){$('#delrow').hide('slow');}}
function delete_row_zip(num){var count=$('#upload_count_zip').val();count=parseInt(count);$('#divrowzip'+num+'').remove();count=parseInt(count)-parseInt(1);$('#upload_count_zip').val(count);if(count<2){$('#delrow').hide('slow');}}
function add_rows(){var count=$('#upload_count').val();var itemcrval=$('#Creq'+count+'').val();if(itemcrval==''){alert('Please Enter Client requirement '+count+'');return false;}var count=parseInt(count)+parseInt(1);var content='';content='<div class="form_block"  id="divrow'+count+'"><p class="fleft" style="margin-right:5px;margin-bottom:2px;width:25%;"><label class="form_label">Client requirement '+count+'<span class="mandatory">*</span></label></p><textarea rows="4" style="width:71%" id="Creq'+count+'" class="text" name="data[ClientRequirements][requirements][]"></textarea><div  class="fright"><p><a href="javascript:void(0)" onclick="javascript:delete_row('+count+')" class="delete_btn" title="Remove">Remove</a></p></div>';$('#upload_container').append(content);$('#upload_count').val(count);}
function add_rows_zip(){var count=$('#upload_count_zip').val();if($('#Zipcode'+count+'').length){var itemcrval=$('#Zipcode'+count+'').val();if(itemcrval==''){alert('Please Enter Zip Code Covered '+count+'');return false;}if((trimSpaces(itemcrval).length>0)&&(trimSpaces(itemcrval).length!=5)){alert('Zip Code Covered '+count+' is not valid.');return false;}}
var count=parseInt(count)+parseInt(1);var content='';content='<div class="form_block" id="divrowzip'+count+'" style="margin-bottom:3px;padding: 5px;"><p class="fleft" style="width:25%;"><label>Zip code covered '+count+'<span class="mandatory">*</span></label></p><div class="fleft" style="width:25%;"><input type="text" maxlength="50" class="text" id="Zipcode'+count+'" name="data[Notary][zipcode][]"></div><div class="float_div1"><p><a href="javascript:void(0)" onclick="javascript:delete_row_zip('+count+')" class="delete_btn" title="Remove">Remove</a></p></div>';$('#upload_container_zip').append(content);$('#upload_count_zip').val(count);}
function add_rows_zipusr(){var count=$('#upload_count_zip').val();if($('#Zipcode'+count+'').length){var itemcrval=$('#Zipcode'+count+'').val();if(itemcrval==''){alert('Please Enter Zip Code Covered '+count+'');return false;}if(trimSpaces(jQuery('#Zipcode'+count+'').val()).length>0&&trimSpaces(jQuery('#Zipcode'+count+'').val()).length!=5){alert('Zip Code Covered '+count+' is not valid.');return false;}}
var count=parseInt(count)+parseInt(1);var content='';content='<div class="form_block" id="divrowzip'+count+'" style="margin-bottom:3px;"><p class="" style="margin-right:10px;width:190px;"><label class="form_label">Zip Code Covered '+count+'<span class="mandatory">*</span></label></p><input type="text" maxlength="50" class="text_box" id="Zipcode'+count+'" name="data[Notary][zipcode][]"><div  class="float_divs"><p><a href="javascript:void(0)" onclick="javascript:delete_row_zip('+count+')" class="delete_btn" title="Remove">Remove</a></p></div>';$('#upload_container_zip').append(content);$('#upload_count_zip').val(count);}
(function($){$.fn.validation=function(){var error=0;$('.required',this).each(function(){var input=$(':input',this).attr("value");var display_name=$(':input',this).attr("id");input=jQuery.trim(input);if(input==""){$(':input',this).addClass("error-highlight");display_name=((display_name.replace('_',' ')).replace('_',' ')).replace('_',' ');error++;display_ch='';var the_length=display_name.length;for(k=0;k<the_length;k++){ch=display_name.charAt(k);if(ch==ch.toUpperCase()){ch=' '+ch;}display_ch=display_ch+ch;}$(':input',this).val('');$(':input',this).focus();alert(display_ch+' is a required field');return false;}else if(display_name.indexOf('Email')!==(-1)){if(!JcheckEmail(input)){$(':input',this).addClass("error-highlight");display_name=((display_name.replace('_','')).replace('_','')).replace('_','');display_ch='';var the_length=display_name.length;for(k=0;k<the_length;k++){ch=display_name.charAt(k);if(ch==ch.toUpperCase()){ch=' '+ch;}display_ch=display_ch+ch;}error++;$(':input',this).focus();alert('Please enter a valid'+display_ch);return false;}else{$('span.error-message',this).remove();$(':input',this).removeClass("error-highlight");}}else{$('span.error-message',this).remove();$(':input',this).removeClass("error-highlight");}});if(error==0){return true;}else{return false;}};})(jQuery);jQuery(document).ready(function(){jQuery("#signupFrm").submit(function(){if(jQuery(this).validation()==true){return true;}return false;});jQuery("#editOrderFrm").submit(function(){if(document.getElementById('DocumentDeliveryReceipt').value=='P'){$("div#puadd").addClass("form_block required");$("div#pustate").addClass("form_block required");$("div#pucity").addClass("form_block required");$("div#puzip").addClass("form_block required");$("div#track").removeClass("float_div3 required");$("div#shpinfo").removeClass("float_div required");}else if(document.getElementById('DocumentDeliveryReceipt').value=='E'){$("div#puadd").removeClass("form_block required");$("div#pustate").removeClass("form_block required");$("div#pucity").removeClass("form_block required");$("div#puzip").removeClass("form_block required");$("div#track").removeClass("float_div3 required");$("div#shpinfo").removeClass("float_div required");}else if(document.getElementById('DocumentDeliveryReceipt').value=='O'){$("div#puadd").removeClass("form_block required");$("div#pustate").removeClass("form_block required");$("div#pucity").removeClass("form_block required");$("div#puzip").removeClass("form_block required");$("div#track").addClass("required");$("div#shpinfo").addClass("required");}
var itemedval=$('#EDOC1').val();if(itemedval!=''){var ext=$('#EDOC1').val().split('.').pop().toLowerCase();var allow=new Array('doc','docx','pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for EDOC 1. Upload file in doc, docx or pdf format!');return false;}}
var itemcnt=$('#upload_count').val();var itemdcval=$('#EDOC'+itemcnt+'').val();if(itemdcval!=''){var ext=itemdcval.split('.').pop().toLowerCase();var allow=new Array('doc','docx','pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for EDOC'+itemcnt+'. Upload file in doc, docx or pdf format!');return false;}}
if(jQuery(this).validation()==true){return true;}return false;});jQuery("#placeOrderFrm").submit(function(){if(document.getElementById('DocumentDeliveryReceipt').value=='P'){$("div#puadd").addClass("form_block required");$("div#pustate").addClass("form_block required");$("div#pucity").addClass("form_block required");$("div#puzip").addClass("form_block required");$("div#track").removeClass("float_div3 required");$("div#shpinfo").removeClass("float_div required");}else if(document.getElementById('DocumentDeliveryReceipt').value=='E'){$("div#puadd").removeClass("form_block required");$("div#pustate").removeClass("form_block required");$("div#pucity").removeClass("form_block required");$("div#puzip").removeClass("form_block required");$("div#track").removeClass("float_div3 required");$("div#shpinfo").removeClass("float_div required");}else if(document.getElementById('DocumentDeliveryReceipt').value=='O'){$("div#puadd").removeClass("form_block required");$("div#pustate").removeClass("form_block required");$("div#pucity").removeClass("form_block required");$("div#puzip").removeClass("form_block required");}
var itemedval=$('#EDOC1').val();if(itemedval!=''){var ext=$('#EDOC1').val().split('.').pop().toLowerCase();var allow=new Array('doc','docx','pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for EDOC 1. Upload file in doc, docx or pdf format!');return false;}}
var itemcnt=$('#upload_count').val();var itemcrval=$('#EDOC'+itemcnt+'').val();if(itemcrval!=''){var ext=itemcrval.split('.').pop().toLowerCase();var allow=new Array('doc','docx','pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for EDOC '+itemcnt+'. Upload file in doc, docx or pdf format!');return false;}}
if(jQuery(this).validation()==true){return confirm('Are you sure you want to place the request?');return true;}return false;});jQuery("#editOrderFrm").submit(function(){if(jQuery(this).validation()==true){return confirm('Are you sure you want to edit order?');if(chkOrd()==true){return true;}}return false;});jQuery("#TutorialAdminEditForm").submit(function(){var itemtfval=$('#TutorialTitle').val();if(itemtfval==''){alert('Please Enter Tutorial Title');jQuery("#TutorialTitle").focus();return false;}
var itemcatgval=$('#TutorialCategory').val();if(itemcatgval==''){alert('Please Enter Tutorial Category');jQuery("#TutorialCategory").focus();return false;}
var itemdsval=$('#TutorialDescription').val();if(itemdsval==''){alert('Please Enter Tutorial Description');jQuery("#TutorialDescription").focus();return false;}
var itemedval=$('#TutorialTutorialfile').val();if(itemedval!=''){var ext=$('#TutorialTutorialfile').val().split('.').pop().toLowerCase();var allow=new Array('mp4','avi','flv','mpeg','wmv');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Tutorial');return false;}}return true;});jQuery("#TutorialAdminAddForm").submit(function(){var itemtfval=$('#TutorialTitle').val();if(itemtfval==''){alert('Please Enter Tutorial Title');jQuery("#TutorialTitle").focus();return false;}
var itemcatgval=$('#TutorialCategory').val();if(itemcatgval==''){alert('Please Enter Tutorial Category');jQuery("#TutorialCategory").focus();return false;}
var itemdsval=$('#TutorialDescription').val();if(itemdsval==''){alert('Please Enter Tutorial Description');jQuery("#TutorialDescription").focus();return false;}
var itemedval=$('#TutorialTutorialfile').val();if(itemedval==''){alert('Please Upload Tutorial');jQuery("#TutorialTutorialfile").focus();return false;}
if(itemedval!=''){var ext=$('#TutorialTutorialfile').val().split('.').pop().toLowerCase();var allow=new Array('mp4','avi','flv','mpeg','wmv');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Tutorial');return false;}}
return true;});jQuery("#NewsAdminEditForm").submit(function(){var itemtfval=$('#NewsTitle').val();if(itemtfval==''){alert('Please Enter  Title');jQuery("#NewsTitle").focus();return false;}
var itemdsval=$('#NewsDescription').val();if(itemdsval==''){alert('Please Enter News Description');jQuery("#NewsDescription").focus();return false;}
var itemedval=$('#NewsImage').val();if(itemedval!=''){var ext=$('#NewsImage').val().split('.').pop().toLowerCase();var allow=new Array('jpg','jpeg','gif','png');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Image File');return false;}}
return true;});jQuery("#NewsAdminAddForm").submit(function(){var itemtfval=$('#NewsTitle').val();if(itemtfval==''){alert('Please Enter News Title');jQuery("#NewsTitle").focus();return false;}
var itemdsval=$('#NewsDescription').val();if(itemdsval==''){alert('Please Enter News Description');jQuery("#NewsDescription").focus();return false;}
var itemedval=$('#NewsImage').val();if(itemedval!=''){var ext=$('#NewsImage').val().split('.').pop().toLowerCase();var allow=new Array('jpg','jpeg','gif','png');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Image File');return false;}}
return true;});jQuery("#InvoiceAdminAddForm").submit(function(){var itemtfval=$('#InvoiceTotalfees').val();if(itemtfval==''){alert('Please Enter Fees');jQuery("#InvoiceTotalfees").focus();return false;}
var itemdsval=$('#InvoiceDoc').val();if(itemdsval==''){alert('Please Enter Invoice');jQuery("#InvoiceDoc").focus();return false;}
if(itemdsval!=''){var ext=$('#InvoiceDoc').val().split('.').pop().toLowerCase();var allow=new Array('pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Invoice Doc');return false;}}
return true;});jQuery("#ResourceAdminEditForm").submit(function(){var itemtfval=$('#ResourceTitle').val();if(itemtfval==''){alert('Please Enter Resource Title');jQuery("#ResourceTitle").focus();return false;}
var itemcatgval=$('#ResourceCategory').val();if(itemcatgval==''){alert('Please Enter Resource Category');jQuery("#ResourceCategory").focus();return false;}
var itemdsval=$('#ResourceDescription').val();if(itemdsval==''){alert('Please Enter Resource Description');jQuery("#ResourceDescription").focus();return false;}
var itemedval=$('#ResourceResourcefile').val();if(itemedval!=''){var ext=$('#ResourceResourcefile').val().split('.').pop().toLowerCase();var allow=new Array('pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Resource file');return false;}}
return true;});jQuery("#ResourceAdminAddForm").submit(function(){var itemtfval=$('#ResourceTitle').val();if(itemtfval==''){alert('Please Enter Resource Title');jQuery("#ResourceTitle").focus();return false;}
var itemcatgval=$('#ResourceCategory').val();if(itemcatgval==''){alert('Please Enter Resource Category');jQuery("#ResourceCategory").focus();return false;}
var itemdsval=$('#ResourceDescription').val();if(itemdsval==''){alert('Please Enter Resource Description');jQuery("#ResourceDescription").focus();return false;}
var itemedval=$('#ResourceResourcefile').val();if(itemedval!=''){var ext=$('#ResourceResourcefile').val().split('.').pop().toLowerCase();var allow=new Array('pdf');if(jQuery.inArray(ext,allow)==-1){alert('Invalid extension for Resource File');return false;}}
return true;});jQuery("#UserChangepasswordForm").submit(function(){if(jQuery(this).validation()==true){if(chekSignup()==true){return true;}}
return false;});jQuery("#odrstatus").submit(function(){if(jQuery(this).validation()==true){return confirm('Are you sure you want change the order status?');return true;}return false;});$("#mailContactForm").submit(function(){if($(this).validation()==true){if(checkEmail(document.getElementById("Email_address").value)){return true;}document.getElementById("Email_address").select();return false;}return false;});$("#UserResetpasswordForm").submit(function(){if($(this).validation()==true){if(checkEmail(document.getElementById("Email_address").value)){return true;}document.getElementById("Email_address").select();return false;}return false;});});function JcheckEmail(emailString){if(emailString.indexOf(' ')>-1){return false;}splitVal=emailString.split('@');if(splitVal.length<=1){return false;}if(splitVal[0].length<=0||splitVal[1].length<=0){return false;}splitDomain=splitVal[1].split('.');if(splitDomain.length<=1){return false;}if(splitDomain[0].length<=0||splitDomain[1].length<=1){return false;}return true;}
function dismisserror(){$(document).ready(function(){$("#aerrordiv").slideToggle("slow");});}setTimeout(function(){$('#aerrordiv').fadeOut('slow');},50000);function loadSearchBox(){$(document).ready(function(){$('#searchdiv').slideToggle("slow");return false;});}
function loadBlock(divid){$(document).ready(function(){$('#'+divid).slideToggle("slow");return false;});}
function loadBlocks(divid,id2){$(document).ready(function(){$('#'+id2).hide();$('#'+divid).slideToggle("slow");return false;});}
function hideBlocks(divid,id2){$(document).ready(function(){$('#'+id2).hide();$('#'+divid).slideToggle("slow");return false;});}
function chekSignup(){if(trimSpaces(jQuery("#Password").val()).length<5){alert('Password should have atleast 5 characters.');jQuery("#Password").focus();return false;}if(trimSpaces(jQuery("#Password").val())!==trimSpaces(jQuery("#ConfirmPassword").val())){alert('Passwords do not match.');jQuery("#ConfirmPassword").focus();return false;}return true;}
function chkSignup(){if(jQuery("#adm_falg").val()==1){if(jQuery("#c_falg").val()==1){if(trimSpaces(jQuery("#OfficeZipcode").val()).length!=5){alert('Office zip code should have  5 digits.');jQuery("#OfficeZipcode").focus();return false;}if(trimSpaces(jQuery("#ReturnZipcode").val()).length!=5){alert('Return zip code should have  5 digits.');jQuery("#ReturnZipcode").focus();return false;}if(document.getElementById("a_falg").value==0){checkcaptcha(document.getElementById("VerificationCode").value);}else{return true;}}else{if(trimSpaces(jQuery("#DocumentZipcode").val()).length!=5){alert('Office zip code should have  5 digits.');jQuery("#DocumentZipcode").focus();return false;}if(trimSpaces(jQuery("#PaymentZipcode").val()).length!=5){alert('Payment zip code should have  5 digits.');jQuery("#PaymentZipcode").focus();return false;}}}}
function chkOrd(){if(trimSpaces(jQuery("#EmailAddress").val())==''){alert('Please enter Email.');jQuery("#Email").focus();return false;}return true;}
function checkEmail(emailString){splitVal=emailString.split('@');if(splitVal.length<=1){alert("Please enter a valid email address ");return false;}if(splitVal[0].length<=0||splitVal[1].length<=0){alert("Please enter a valid email address ");return false;}splitDomain=splitVal[1].split('.');if(splitDomain.length<=1){alert("Please enter a valid email address  ");return false;}if(splitDomain[0].length<=0||splitDomain[1].length<=1){alert("Please enter a valid email address  ");return false;}return true;}
function doEvent(){$("#inplace").hide();$("#change").click(function(){$(this).hide();$("#inplace").show();jQuery("#testing").hide();return true;});}
function show(){jQuery("#testing").hide();jQuery("#inplace").show();}
function doChange(sitepath,orderid){jQuery.post(sitepath+"orders/ajaxsave",{id:orderid,orderstatus_id:jQuery("#idstatus").val()},function(data){if(data!=="0"){jQuery("#testing").html(data+' <a  style="cursor:pointer;" id="change" onClick="show();">change</a>');jQuery("#testing").show();jQuery("#inplace").hide();}else{jQuery("#inplace").show();jQuery("#change").hide();}});}
function add_ref(){var howhr=$('#how_did_u_hear').val();content='<label>Referred by</label></td><td><input type="text" maxlength="255" class="text" id="how_hear_ref" name="data[Notary][how_hear_ref]">';if(howhr=='R'){$('#ref_container').html(content);}}
function add_appt(){var howhr=$('#OrderStatus').val();content='<label>Referred by</label></td><td><input type="text" maxlength="255" class="text" id="how_hear_ref" name="data[Notary][how_hear_ref]">';if(howhr=='4'){$('#add_container').html(content);}}
function approvenotes(shid){$("#notr"+shid).slideToggle("fast");$.get(base_url+"signinghistories/changestatus/"+shid,function(data){$('#changestatusdiv'+shid).html(data);jQuery("#changestatusdiv"+shid).show();});}
function hidestatus(shid){$("#notr"+shid).slideToggle("fast");}
function getclient(value){$.get(baseurl+"users/check_client/"+value,function(data){$('#errordiv').html(data);});}$(document).ready(function(){$('#morelinks').click(function(){$('div.morelinksdiv').slideToggle('medium');});});function closebox(id){$(document).ready(function(){$("#"+id).slideToggle("slow");});}$(document).ready(function(){$("#CompanyPhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#CompanyPhone").val(curval+"-");}else if(curchr==7){$("#CompanyPhone").val(curval+"-");}});});$(document).ready(function(){$("#DayPhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#DayPhone").val(curval+"-");}else if(curchr==7){$("#DayPhone").val(curval+"-");}});});$(document).ready(function(){$("#EveningPhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#EveningPhone").val(curval+"-");}else if(curchr==7){$("#EveningPhone").val(curval+"-");}});});$(document).ready(function(){$("#HomePhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#HomePhone").val(curval+"-");}else if(curchr==7){$("#HomePhone").val(curval+"-");}});});$(document).ready(function(){$("#WorkPhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#WorkPhone").val(curval+"-");}else if(curchr==7){$("#WorkPhone").val(curval+"-");}});});$(document).ready(function(){$("#CellPhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#CellPhone").val(curval+"-");}else if(curchr==7){$("#CellPhone").val(curval+"-");}});});$(document).ready(function(){$("#AlternativePhone").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#AlternativePhone").val(curval+"-");}else if(curchr==7){$("#AlternativePhone").val(curval+"-");}});});$(document).ready(function(){$("#CompanyFax").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#CompanyFax").val(curval+"-");}else if(curchr==7){$("#CompanyFax").val(curval+"-");}});});$(document).ready(function(){$("#Fax").keyup(function(){var curchr=this.value.length;var curval=$(this).val();if(curchr==3){$("#Fax").val(curval+"-");}else if(curchr==7){$("#Fax").val(curval+"-");}});});function updateNotary(){$(document).ready(function(){$("#msgcnt").slideToggle("slow");});}